spring:
  application:
    name: demo

# Docs API??
springdoc:
  swagger-ui:
    # API??, ????:swagger-ui/index.html, ??http://localhost:8080/docs/index.html??
    path: /docs/index.html
    # ??Swagger UI??
    enabled: true
    # ??HTTP???API??????
    operations-sorter: method
  api-docs:
    # OpenAPI??????????:/v3/api-docs, ??http://localhost:8080/docs/api??????
    # OpenAPI???????JSON??, ??http://localhost:8080/docs/api.yaml??yaml??
    path: /docs/api
    # ??api-docs
    enabled: true
  # ????????????????
  packages-to-scan: cn.ybzy.demo
  # ???????????????
  paths-to-match:  /test/**,/user/**
